// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXy3y6rzd0i6iZVWxWpyOR0ed9rVbe46I',
    appId: '1:18879609992:android:2fdcf74639e84590afb33d',
    messagingSenderId: '18879609992',
    projectId: 'flutter-ecommerce-bloc-text',
    storageBucket: 'flutter-ecommerce-bloc-text.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTWLnlsOVu1vGBgu2gv-mSPUja-QVfJcQ',
    appId: '1:18879609992:ios:3bde2243a20a2feaafb33d',
    messagingSenderId: '18879609992',
    projectId: 'flutter-ecommerce-bloc-text',
    storageBucket: 'flutter-ecommerce-bloc-text.appspot.com',
    iosClientId: '18879609992-io84o99ugnmt0rlvkbdf0n07lm36c3s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );
}
